# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  windows-core:
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure
        run: cmake --preset windows-vs2022

      - name: Build Debug
        run: cmake --build --preset windows-debug

      - name: Test Debug
        run: ctest --preset windows-debug

      - name: Build Release
        run: cmake --build --preset windows-release

      - name: Test Release
        run: ctest --preset windows-release
